Fixing the 404 error
gautamkrishnar/socli pull request #217
Opened 2020-09-13 16:33 UTC by suvhotta

Did the necessary changes to fix #212 
Please review the same and lemme know if I need to change something.

2020-09-14 13:15 UTC, gautamkrishnar requested changes
@suvhotta This will break #211 
Please revert this change and handle the `IndexError` on https://github.com/gautamkrishnar/socli/blob/master/socli/socli.py#L419 like:
```python
        if display_condition:
            open_in_browser = False
            try:
                display_results(url_to_use)
            except IndexError:
                printer.print_fail("The URL specified is returning a 404, please check the url and try again!")
                exit(0)
```

2020-09-14 15:26 UTC, suvhotta commented
@gautamkrishnar I'd placed a check to verify if the domain used in the url is 'stackoverflow.com' or something else. But as you cleared in #212 that other urls can also be supported, should I keep that or remove it?

2020-09-14 15:28 UTC, gautamkrishnar commented
@suvhotta Stackoverlow domain check is not required.

2020-09-14 15:55 UTC, suvhotta commented
@gautamkrishnar I checked #211 and found that it was to fix the IndexError. But I think that is something which can occur when we are trying to form a valid url by integrating the query entered by user with the so_url. But here since the url is directly provided by the user, then I think we might not get this scenario of IndexError. Please correct me if my understanding is wrong somewhere.

2020-09-14 16:05 UTC, gautamkrishnar commented
@suvhotta you will get an indexerror even though user has provided the url. I had tested it out locally, you can do that too. Indexerror is triggered by the `get_question_stats_and_answer` function.

2020-09-15 07:06 UTC, gautamkrishnar commented
@suvhotta please do `git checkout master --- socli/search.py` to revert the file changes completely so that it wont appear in the PR.

2020-09-15 07:09 UTC, gautamkrishnar approved these changes

2020-09-15 07:10 UTC, merged