fix potential bug risks and anti-patterns
gautamkrishnar/socli pull request #248
Opened 2021-01-03 19:14 UTC by tusharnankani

2021-01-07 20:34 UTC, gautamkrishnar commented
@tusharnankani thanks for contributing, will have a look at it when I have time 😄

2021-01-07 20:43 UTC, gautamkrishnar commented
@tusharnankani are you contributing as the part of DWOC (https://devscript.tech/woc/) ?

2021-01-08 05:23 UTC, tusharnankani commented
> @tusharnankani are you contributing as the part of DWOC (https://devscript.tech/woc/) ?

Yes.

2021-01-17 09:43 UTC, gautamkrishnar requested changes
@tusharnankani please answer the comments

2021-01-17 09:43 UTC, gautamkrishnar commented on socli/search.py
> +                            if qna in ["b", "B"]:
@tusharnankani can you please explain why you changed elif to if?

2021-01-17 09:43 UTC, gautamkrishnar commented on socli/search.py
> +                            if qna in ["o", "O"]:
Here as well?

2021-01-17 09:43 UTC, gautamkrishnar commented on socli/search.py
> +                            if qna in ["o", "O"]:
And all other places?

2021-01-17 09:45 UTC, gautamkrishnar commented
@tusharnankani I am not sure why you modified lots of if statements, there is a difference between using if-else and if only.

2021-01-17 09:55 UTC, tusharnankani commented
@gautamkrishnar 

Apologies for the confusion, I should have written what changes I made, and why. This PR includes:
- The else / elif block here is unnecessary because the leading if block has a `continue` statement, or any other statement, like `break`, or `return`. These come under anti-patterns,
  - These statements causes the control flow to be disrupted, making the else / elif block here unnecessary. This doesn't mean you can not use it, but it is recommended to refactor this for a better readability.
- Used `sys.exit()`, 
- Import alias same as the original package name
- Simplified if expression - `bool(namespace.json)`
- remove unnecessary `dict()` calls
  - It is slower to call e.g. `dict()` than using the empty literal - `{}`, because the name dict must be looked up in the global scope in case it has been rebound. Same for the other two types like list() and tuple().

2021-01-17 10:01 UTC, gautamkrishnar approved these changes

2021-01-17 10:03 UTC, merged

2021-01-17 10:03 UTC, gautamkrishnar commented
@tusharnankani thanks a lot for the contribution 🎉 

@all-contributors please add @tusharnankani for code